-record(enet_peer,
        {
         handshake_flow,
         peer_id,
         ip,
         port,
         name,
         manager_name,
         host,
         channels,
         connect_fun,
         connect_packet_data
        }).
